version: '3'

services:
    timothe:
        build: .
        image: ghcr.io/matthieucoder/timothe-rs:main
        environment:
            - RUST_LOG=info
        volumes:
            - ./config.toml:/app/config.toml